---
# tasks file for lighthouse-role
- name: Install EPEL
  become: true
  ansible.builtin.yum:
    name: "epel-release"
    state: latest
- name: Install Nginx & Git
  become: true
  ansible.builtin.yum:
    name:
      - nginx
      - git
    state: latest
- name: Start Nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: started
- name: Autorun Nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
- name: Install FireWall
  become: true
  ansible.builtin.yum:
    name: "firewalld"
    state: latest
- name: Start FireWall
  become: true
  ansible.builtin.systemd:
    name: firewalld
    state: started
- name: Upgrade FireWall
  become: true
  ansible.builtin.command:
    cmd: "{{ item }}"
  with_items:
    - firewall-cmd --zone=public --permanent --add-service=http
    - firewall-cmd --zone=public --permanent --add-service=https
    - firewall-cmd --reload
- name: Create directory
  become: true
  ansible.builtin.file:
    path: /var/www/lighthouse
    state: directory
    owner: nginx
    group: nginx
    mode: "0755"
- name: Clone repository Lighthouse
  become: true
  ansible.builtin.command:
    cmd: "{{ item }}"
  with_items:
    - git clone https://github.com/VKCOM/lighthouse.git /usr/share/nginx/lighthouse
    - sed -i 's|/usr/share/nginx/html|/usr/share/nginx/lighthouse|' /etc/nginx/nginx.conf
- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted