---
- name: Download Vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.amd64.deb"
    dest: "./vector-{{ vector_version }}-1.amd64.deb"
