---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos_7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: centos_8
    image: docker.io/psvitov/centos8_update      
    pre_build_image: true
  - name: ubuntu
    image: docker.io/psvitov/ubuntu_python
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
