---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_7
    image: centos:7
    pre_build_image: true
  - name: centos_8
    image: psvitov/centos8_update      
    pre_build_image: true
  - name: ubuntu
    image: psvitov/ubuntu_python
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
